name: learntech
description: A project by NSS Genics, aimed at elderlies, to teach the usage of WhatsApp and how to stay safe online.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  auto_size_text: ^1.1.2
  http: ^0.12.0+2
  preload_page_view: ^0.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/LoadingScreen/AppLogo.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/Background/wallpaper.png
    - assets/Side/SideBar_JewelChangi.png
    - assets/LoadingScreen/Cloud.png
    - assets/LoadingScreen/IPhoneX.png
    - assets/LoadingScreen/LeftTopArrow.png
    - assets/LoadingScreen/RightBottomArrow.png
    - assets/Logo/AppLogo.png
    - assets/Logo/WhatsApp.png
    - assets/Logo/lock.png
    - assets/WhatsAppTopics/InstallingWhatsApp.jpg
    - assets/WhatsAppTopics/CreatingAnAccount.jpg
    - assets/WhatsAppTopics/AddingContacts.jpg
    - assets/WhatsAppTopics/AnsweringCalls.jpg
    - assets/WhatsAppTopics/SendingMessages.jpg
    - assets/WhatsAppTopics/SendingVoiceMemos.jpg
    - assets/WhatsAppTopics/SendingMedia.jpg
    - assets/WhatsAppTopics/ManagingCalls.jpg
    - assets/WhatsAppTopics/CreatingGroupChats.jpg
    - assets/SecurityTopics/IncreasePrivacy.jpg
    - assets/SecurityTopics/DetectingScams.jpg
    - assets/SecurityTopics/DetectingFakeNews.jpg
    - assets/SecurityTopics/Scam.jpg
    - assets/SecurityTopics/FakeNews.jpg
#    - assets/WhatsAppTopics/iOS/FindInstallSearch.gif
#    - assets/WhatsAppTopics/iOS/CreatingAnAccount.gif
#    - assets/WhatsAppTopics/iOS/AddingContacts.gif
#    - assets/WhatsAppTopics/iOS/SendingMessages.gif
#    - assets/WhatsAppTopics/iOS/SendingVoiceMemos.gif
#    - assets/WhatsAppTopics/iOS/SendingPhotos.gif
#    - assets/WhatsAppTopics/iOS/SendingLocation.gif
#    - assets/WhatsAppTopics/iOS/GivingCalls.gif
#    - assets/WhatsAppTopics/iOS/AddingContactstoGroup.gif
#    - assets/WhatsAppTopics/iOS/CreatingGroups.gif
#    - assets/WhatsAppTopics/iOS/LastSeen.gif
#    - assets/WhatsAppTopics/iOS/ReceivingCall.jpg
#    - assets/WhatsAppTopics/iOS/Answering.gif
#    - assets/WhatsAppTopics/iOS/Declining.gif
#    - assets/WhatsAppTopics/iOS/ReportBlock.gif
    - assets/WhatsAppTopics/Android/FindInstallSearch1.png
    - assets/WhatsAppTopics/Android/FindInstallSearch2.jpg
    - assets/WhatsAppTopics/Android/CreatingAnAccount.gif
    - assets/WhatsAppTopics/Android/AddingContacts.gif
    - assets/WhatsAppTopics/Android/SendingMessages.gif
    - assets/WhatsAppTopics/Android/SendingVoiceMemos.gif
    - assets/WhatsAppTopics/Android/SendingPhotos.gif
#    - assets/WhatsAppTopics/Android/SendingLocation.gif
    - assets/WhatsAppTopics/Android/GivingCalls.gif
    - assets/WhatsAppTopics/Android/ReceivingCall.jpg
    - assets/WhatsAppTopics/Android/AddingContactstoGroup.gif
    - assets/WhatsAppTopics/Android/Declining.gif
    - assets/WhatsAppTopics/Android/Answering.gif
    - assets/WhatsAppTopics/Android/LastSeen.gif
    - assets/WhatsAppTopics/Android/ReportBlock.gif





  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
